pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: "*pivotal"
pivnet-product-slug: "pivotal-container-service"
product-version-regex: 1\.4\.(.*)
download-stemcell: "true"
stemcell-iaas: "google"
